# To overcome the CrashLoopBack error in Windows 10 Pro
kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
  # Changed this  based on https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql
    #path: "/mnt"
    path: "/mnt/data"