# Purpose is to tell the cert manager where it shouold go to get a certficate
# We need an issuer object but there's no apiVersion for it. It's defined by the cert manager we installed
# This says reach into the certmanager bucket of objects. We want to create a issuer type object
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'lerman@runbox.com'
    privateKeySecretRef:
      # This is not connected to the secret related to the certificate
      name: letsencrypt-prod
    http01: {}